// 💡 全局唯一配置中心。新建 App 或 Fork 模板后，只需在此修改应用名、包名及 GitHub 仓库即可！
ext {
    // 应用基础配置
    applicationId = "com.slowpack.androidtemplate"
    appName = "android-template"
    
    // GitHub 自动更新配置
    githubOwner = "slowpack"
    githubRepo = "android-template"
    
    // 版本控制，本地脚本与 CI 脚本会自动对其进行自增
    versionCode = 2
    versionName = "1.0.1"
}
